//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaInterna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int IdPago { get; set; }
        public int IdDocumento { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MontoPago { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Documentos Documentos { get; set; }
    }
}
