//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaInterna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.Documentos = new HashSet<Documentos>();
        }
    
        public int IdProyecto { get; set; }
        public int IdEmpresa { get; set; }
        public int IdUsuarioCargo { get; set; }
        public string NombreProyecto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Aprobado { get; set; }
        public decimal MontoProyecto { get; set; }
        public System.DateTime FechaPago { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public bool Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
